language: python
python:
  - 3.6
before_install:
  - sudo rm -f /etc/boto.cfg
  # Remove when this is solved https://github.com/spulec/moto/pull/1952
  - export AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
  - export AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
install:
  - pip install codecov tox-travis
script:
  - tox
after_success:
  - codecov
notifications:
  email: false
